### ISSUE TITLE
Angular module is not able to load.

### ISSUE THREAD

**Issue by Vishwas1** [Vishwas1/DataPower_Cert_Manager#2]
Angular module is not able to load inn index.html. Expected reason may be :  the path provided for angapp.js file is incorrect

**Comment by Vishwas1** [comment]
Thisi issue is fixed and checked in.

**Comment by vikramIde** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Install Node Js](https://trello.com/c/X8eQtAXP/1-install-node-js)

**Comment by Vishwas1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [All Issues](https://trello.com/c/LYqhdE4s/13-all-issues)
