### ISSUE TITLE
cannot find module ejs on the branch master

### ISSUE THREAD

**Issue by vikramIde** [Vishwas1/DataPower_Cert_Manager#20]
When doing npm start 

cannot find module ejs on the branch master

**Comment by vikramIde** [comment]
Fixed !

issue was due to missing new package EJS which is used for using HTML as VIew engine in NODE

solution : npm install

**Comment by vikramIde** [comment]
Fixed !

issue was due to missing new package EJS which is used for using HTML as VIew engine in NODE

solution : npm install

**Comment by Vishwas1** [comment]
Bravo!
