### ISSUE TITLE
.env file should not be checked in.

### ISSUE THREAD

**Issue by Vishwas1** [Vishwas1/DataPower_Cert_Manager#3]
.env file should not be checked in.

**Comment by vikramIde** [comment]
fixed added the .env file to gitignore

**Comment by vikramIde** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Install Node Js](https://trello.com/c/X8eQtAXP/1-install-node-js)

**Comment by Vishwas1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [All Issues](https://trello.com/c/LYqhdE4s/13-all-issues)
